[package]
name = "shifty"
version = "0.1.0"
edition = "2021"
publish = ["afo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
chrono-tz = "0.9.0"
thiserror = "1.0.61"
